plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Paul Sztajer (PDYXS)
url: http://pdyxs.wtf
encoding: utf-8
author: paul
twitter:
  username: pdyxs
logo: /who/profile.jpg
exclude:
  - image-resizer
social:
  name: Paul Sztajer
  links:
    - https://twitter.com/pdyxs
    - https://facebook.com/pdyxs
    - http://instagram.com/pdyxs
    - http://medium.com/@pdyxs
    - http://linkedin.com/in/pdyxs
    - https://github.com/pdyxs
google-site-verification: google62ea18a3dcb04445.html
collections_dir: collections
collections:
  arctic:
    output: true
  galapagos:
    output: true
  fatecardgame:
    output: true
  drafts:
    output: true
  pastprojects:
    output: true
  currentprojects:
    output: true
  futureprojects:
    output: true
  places:
    output: true
  stories:
    output: true
  services:
    output: false
  who:
    output: false
  what:
    output: false
  where:
    output: false
  when:
    output: false
  why:
    output: false
  workhistory:
    output: true
defaults:
  - scope:
      path: ""
      type: arctic
    values:
      category: arctic
      layout: inner/story-item
  - scope:
      path: ""
      type: galapagos
    values:
      category: galapagos
      layout: inner/story-item
  - scope:
      path: ""
      type: fatecardgame
    values:
      category: fatecardgame
      layout: inner/story-item
  - scope:
      path: ""
      type: pastprojects
    values:
      layout: project
      permalink: /what/projects/:title
  - scope:
      path: ""
      type: futureprojects
    values:
      layout: project
      permalink: /what/projects/:title
  - scope:
      path: ""
      type: currentprojects
    values:
      layout: project
      permalink: /what/projects/:title
  - scope:
      path: ""
      type: places
    values:
      layout: story
      permalink: /where/:title
  - scope:
      path: ""
      type: stories
    values:
      layout: story
      permalink: /stories/:title
  - scope:
      path: ""
      type: drafts
    values:
      permalink: /drafts/:title
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /what/blog/:title
  - scope:
      path: ""
      type: services
    values:
      layout: inner/service-item
