plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Paul Sztajer (PDYXS)
url: http://pdyxs.wtf
author: paul
twitter:
  username: pdyxs
logo: /who/profile.jpg
social:
  name: Paul Sztajer
  links:
    - https://twitter.com/pdyxs
    - https://facebook.com/pdyxs
    - http://instagram.com/pdyxs
    - http://medium.com/@pdyxs
    - http://linkedin.com/in/pdyxs
    - https://github.com/pdyxs
google-site-verification: google62ea18a3dcb04445.html
collections_dir: collections
collections:
  arctic:
    output: true
  pastprojects:
    output: true
  currentprojects:
    output: true
  places:
    output: true
  services:
    output: false
  who:
    output: false
  what:
    output: false
  where:
    output: false
  when:
    output: false
  why:
    output: false
  how:
    output: false
defaults:
  - scope:
      path: ""
      type: arctic
    values:
      category: arctic
      layout: inner/story-item
  - scope:
      path: ""
      type: pastprojects
    values:
      layout: project
      permalink: /what/projects/:title
  - scope:
      path: ""
      type: currentprojects
    values:
      layout: project
      permalink: /what/projects/:title
  - scope:
      path: ""
      type: places
    values:
      layout: story
      permalink: /where/:title
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /what/blog/:title
  - scope:
      path: ""
      type: services
    values:
      layout: inner/service-item
