// Codegen: dithered greyscale surfaces as CSS custom properties, usable directly
// as `background: var(--dither-N)`. Emits src/styles/dither.generated.css, which
// global.css @imports. Runs via the `prebuild` npm script (and `npm run gen:dither`).
//
// Method: radial-gradient encoding ("dots"), 4px tile, 4x4 Bayer, levels 0..16
// (0 = paper … 16 = ink). Colours stay live var(--color-text)/var(--color-bg), so
// the set is theme-aware with NO dark override and never needs regenerating when a
// colour token changes — only if TILE or the matrix changes.
//
// Two var sets:
//   --dither-N      full surface  (opaque paper base; inverted past 50% to cap the
//                                  layer count). Use as `background: var(--dither-6)`.
//   --dither-ink-N  ink-only OVERLAY (dots on transparent, never inverted). Fade one
//                   of these over a --dither base to "grow" between levels — because
//                   ordered levels are additive supersets, only the added cells fade
//                   in. See the pure-CSS hover pattern in the experiment page.
//
// Print: a @media print block redefines every var to a flat colour-mix grey (and the
// ink overlays to transparent), so any dithered surface reproduces as solid grey.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const TILE = 4; // px — 4px/4 = 1px cells, pixel-aligned (5px's 1.25px cells alias)
const N = 4; // 4x4 Bayer
const CELLS = N * N; // 16
const CELL = TILE / N; // 1px
const DOT_R = +Math.sqrt(CELL ** 2 / Math.PI).toFixed(3); // dot area ≈ cell area

const BAYER4 = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5];

const cx = (i) => +(((i % N) + 0.5) * CELL).toFixed(4);
const cy = (i) => +((Math.floor(i / N) + 0.5) * CELL).toFixed(4);
// `fixed` is load-bearing, not decoration. Without it a layer's background
// positioning area is the ELEMENT's box, so the pattern travels with the
// element: scroll or animate it and the sub-pixel dots (DOT_R ≈ 0.564px in 1px
// cells) are re-rasterised at a new phase every frame, and the surface visibly
// shimmers. Anchoring to the viewport instead means one global dot grid that
// never moves — elements just clip their window onto it, and every level stays
// in phase with every other.
//
// It has to live inside the token: consumers write `background: var(--dither-N)`,
// and the `background` shorthand RESETS background-attachment, so a separate
// longhand would have to follow the shorthand at all ~49 call sites.
const dot = (i, color) =>
  `radial-gradient(circle at ${cx(i)}px ${cy(i)}px, ${color} ${DOT_R}px, #0000 ${DOT_R + 0.02}px) 0 0/${TILE}px ${TILE}px fixed`;

// Full surface: opaque paper base, ink dots — inverted past 50% to cap layers.
function full(level) {
  if (level <= 0) return 'var(--color-bg)';
  if (level >= CELLS) return 'var(--color-text)';
  const inkDots = level <= CELLS / 2;
  const dotColor = inkDots ? 'var(--color-text)' : 'var(--color-bg)';
  const bgColor = inkDots ? 'var(--color-bg)' : 'var(--color-text)';
  const cells = [];
  for (let i = 0; i < CELLS; i++) {
    const on = BAYER4[i] < level;
    if (inkDots ? on : !on) cells.push(i);
  }
  return `${cells.map((i) => dot(i, dotColor)).join(', ')}, ${bgColor}`;
}

// Ink-only overlay: dots on transparent, NEVER inverted (superset math for grow).
function ink(level) {
  if (level <= 0) return 'none';
  const cells = [];
  for (let i = 0; i < CELLS; i++) if (BAYER4[i] < level) cells.push(i);
  return cells.map((i) => dot(i, 'var(--color-text)')).join(', ');
}

// Flat print fallback: N/16 of the way from paper to ink.
const flat = (level) =>
  `color-mix(in srgb, var(--color-text) ${((level / CELLS) * 100).toFixed(2)}%, var(--color-bg))`;

const levels = Array.from({ length: CELLS + 1 }, (_, k) => k); // 0..16

const css = `/* AUTO-GENERATED by scripts/gen-dither.mjs — do not edit by hand.
   ${TILE}px tile, ${N}x${N} Bayer, ${CELLS + 1} levels (0 = paper … ${CELLS} = ink).
   Method A (radial dots), theme-aware via live var() colours.
   Usage:  background: var(--dither-6);
   Grow between levels: fade var(--dither-ink-<target>) over a var(--dither-<source>)
   base (opacity 0→1). Keep dither off text surfaces (contrast).

   Every layer is background-attachment: fixed — the dot grid is anchored to the
   VIEWPORT, and an element only clips its window onto it, so a moving or
   scrolling element never re-rasterises the pattern. Caveat: a transform /
   filter / backdrop-filter / will-change / contain:paint / perspective on any
   ANCESTOR re-anchors the background to that ancestor and silently restores the
   shimmer. See CLAUDE.md. */
:root {
${levels.map((k) => `  --dither-${k}: ${full(k)};`).join('\n')}

${levels.map((k) => `  --dither-ink-${k}: ${ink(k)};`).join('\n')}
}

@media print {
  :root {
${levels.map((k) => `    --dither-${k}: ${flat(k)};`).join('\n')}
${levels.map((k) => `    --dither-ink-${k}: transparent;`).join('\n')}
  }
}
`;

const outFile = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'styles', 'dither.generated.css');
writeFileSync(outFile, css);
console.log(`Wrote ${outFile} (${css.length} bytes) — method A, ${TILE}px, ${levels.length} levels x2 sets`);
