// GENERATED by scripts/generate-header-previews.mjs — do not edit.
// One entry per card with a `headerMedia:` island, mapping to the stills
// screenshotted from it. `hash` is what decides a re-shoot; the paths are
// public/ URLs, ready for <img src>.

export type HeaderPreview = { light: string; dark: string; hash: string };

export const HEADER_PREVIEWS: Record<string, HeaderPreview> = {
  "what/art/lino-printing": {"light":"/previews/what/art/lino-printing/light.png","dark":"/previews/what/art/lino-printing/dark.png","hash":"a98206dfd82b2568"},
  "what/toys/star-navigation": {"light":"/previews/what/toys/star-navigation/light.png","dark":"/previews/what/toys/star-navigation/dark.png","hash":"a98206dfd82b2568"},
};
