// AUTO-GENERATED by scripts/generate-lens-registry.mjs — do not edit by hand.
// Source: src/content/<dimension>/<id>.lens.yaml. Regenerated on predev/prebuild.
import type { LensDeclaration } from '../lib/lens-registry.ts';

export const LENS_DECLARATIONS: LensDeclaration[] = [
  {
    "id": "home",
    "dimension": "what",
    "label": "A bit of everything",
    "subtitle": "Paul Sztajer — games, puzzles, writing and work",
    "icon": "scatter",
    "component": "home",
    "acceptsFilters": false,
    "config": {
      "slots": [
        {
          "type": "pinned",
          "uid": "who/about-me"
        },
        {
          "type": "filter",
          "label": "A Project",
          "pool": 5,
          "filter": {
            "what": [
              "what:games",
              "what:art",
              "what:software"
            ]
          }
        },
        {
          "type": "filter",
          "label": "A Puzzle",
          "pool": 5,
          "filter": {
            "what": [
              "what:puzzles"
            ]
          }
        },
        {
          "type": "filter",
          "label": "A Post",
          "pool": 5,
          "filter": {
            "what": [
              "what:writing"
            ]
          }
        }
      ]
    }
  },
  {
    "id": "interesting",
    "dimension": "what",
    "label": "Most* Interesting",
    "note": "*an attempt at that, anyway",
    "icon": "interesting",
    "component": "interesting",
    "width": "960px",
    "config": {
      "sortKey": "ranking"
    }
  },
  {
    "id": "editorial",
    "dimension": "what",
    "label": "Editorial",
    "icon": "flag",
    "component": "editorial",
    "width": "960px",
    "devOnly": true
  },
  {
    "id": "audit",
    "dimension": "what",
    "label": "Audit",
    "icon": "dot",
    "component": "audit",
    "width": "960px",
    "acceptsFilters": false,
    "devOnly": true
  },
  {
    "id": "newest",
    "dimension": "when",
    "label": "Newest",
    "icon": "timeline",
    "component": "newest",
    "width": "960px",
    "config": {
      "sortKey": "date",
      "sortDirection": "desc",
      "display": "strip",
      "limit": 30
    }
  },
  {
    "id": "oldest",
    "dimension": "when",
    "label": "Oldest",
    "icon": "timeline-oldest",
    "component": "oldest",
    "width": "960px",
    "config": {
      "sortKey": "date",
      "sortDirection": "asc",
      "display": "strip",
      "limit": 30
    }
  },
  {
    "id": "seen",
    "dimension": "when",
    "label": "Seen",
    "icon": "seen",
    "component": "history",
    "width": "960px",
    "config": {
      "readState": "seen"
    }
  },
  {
    "id": "unseen",
    "dimension": "when",
    "label": "Unseen",
    "icon": "unseen",
    "component": "history",
    "width": "960px",
    "config": {
      "readState": "unseen"
    }
  }
];
