// AUTO-GENERATED by scripts/generate-lens-icons.mjs — do not edit by hand.
// Source: src/icons/lenses/*.svg. Regenerated on predev/prebuild.
import type { LensIconDef } from '../lib/lens-icons.ts';

export const LENS_ICON_DEFS: Record<string, LensIconDef> = {
  "dot": {
    filled: true,
    shapes: [
      { kind: 'path', d: "M12 8a4 4 0 1 0 0 8 4 4 0 1 0 0-8" },
    ],
  },
  "flag": {
    filled: false,
    shapes: [
      { kind: 'path', d: "M6 3v18M6 4h12l-4 5 4 5H6" },
    ],
  },
  "scatter": {
    filled: true,
    shapes: [
      { kind: 'path', d: "M4.308 2.503a2.436 2.436 0 1 0 0 4.871 2.436 2.436 0 1 0 0-4.87m5.048.736a1.7 1.7 0 1 0 0 3.4 1.7 1.7 0 1 0 0-3.4M18.94 8.6a1.7 1.7 0 1 0 0 3.4 1.7 1.7 0 1 0 0-3.4M3.947 13.3a1.7 1.7 0 1 0 0 3.4 1.7 1.7 0 1 0 0-3.4m10.001-4.896a2.648 2.648 0 1 0 0 5.296 2.648 2.648 0 1 0 0-5.296M19.47 13.3a2.23 2.23 0 1 0 0 4.46 2.23 2.23 0 1 0 0-4.46M6.267 16.814a2.32 2.414 0 1 0 0 4.828 2.32 2.414 0 1 0 0-4.828m8.411 2.12a1.31 1.354 0 1 0 0 2.707 1.31 1.354 0 1 0 0-2.707" },
    ],
  },
  "timeline-oldest": {
    filled: false,
    shapes: [
      { kind: 'path', d: "M20.5 5.5v13M3.5 12h17m-6-2.5v5M9 9.5v5M7 8l-4 4 4 4" },
    ],
  },
  "timeline": {
    filled: false,
    shapes: [
      { kind: 'path', d: "M3.5 5.5v13m0-6.5h17m-11-2.5v5m5.5-5v5M17 8l4 4-4 4" },
    ],
  }
};
