// AUTO-GENERATED by scripts/generate-lens-registry.mjs — do not edit by hand.
// Source: src/content/<dimension>/<id>.lens.yaml. Regenerated on predev/prebuild.
import type { LensDeclaration } from '../lib/lens-registry.ts';

export const LENS_DECLARATIONS: LensDeclaration[] = [
  {
    "id": "home",
    "dimension": "what",
    "label": "A bit of everything",
    "icon": "scatter",
    "component": "home",
    "acceptsFilters": false,
    "config": {
      "slots": [
        {
          "type": "pinned",
          "uid": "who/about-me"
        },
        {
          "type": "filter",
          "label": "A Project",
          "filter": {
            "what": [
              "what:games",
              "what:art",
              "what:software"
            ]
          }
        },
        {
          "type": "filter",
          "label": "A Puzzle",
          "filter": {
            "what": [
              "what:puzzles"
            ]
          }
        },
        {
          "type": "filter",
          "label": "A Post",
          "filter": {
            "what": [
              "what:writing"
            ]
          }
        }
      ]
    }
  },
  {
    "id": "editorial",
    "dimension": "what",
    "label": "Editorial",
    "icon": "flag",
    "component": "editorial",
    "width": "960px",
    "devOnly": true
  },
  {
    "id": "audit",
    "dimension": "what",
    "label": "Audit",
    "icon": "dot",
    "component": "audit",
    "width": "960px",
    "acceptsFilters": false,
    "devOnly": true
  },
  {
    "id": "newest",
    "dimension": "when",
    "label": "Newest",
    "icon": "timeline",
    "component": "newest",
    "width": "960px",
    "config": {
      "sortKey": "date",
      "sortDirection": "desc",
      "limit": 100
    }
  },
  {
    "id": "oldest",
    "dimension": "when",
    "label": "Oldest",
    "icon": "timeline-oldest",
    "component": "oldest",
    "width": "960px",
    "config": {
      "sortKey": "date",
      "sortDirection": "asc",
      "limit": 6
    }
  }
];
