// AUTO-GENERATED by scripts/generate-lens-icons.mjs — do not edit by hand.
// Source: src/icons/lenses/*.svg. Regenerated on predev/prebuild.
import type { LensIconDef } from '../lib/lens-icons.ts';

export const LENS_ICON_DEFS: Record<string, LensIconDef> = {
  "dot": {
    filled: true,
    shapes: [
      { kind: 'path', d: "M12 8a4 4 0 1 0 0 8 4 4 0 1 0 0-8" },
    ],
  },
  "flag": {
    filled: false,
    shapes: [
      { kind: 'path', d: "M6 3v18M6 4h12l-4 5 4 5H6" },
    ],
  },
  "scatter": {
    filled: true,
    shapes: [
      { kind: 'path', d: "M4.396 1.082a4.233 4.25 0 1 0 0 8.502 4.233 4.25 0 1 0 0-8.502M22.24 6.185a1.7 1.7 0 1 0 0 3.4 1.7 1.7 0 1 0 0-3.4M3.947 13.3a1.7 1.7 0 1 0 0 3.4 1.7 1.7 0 1 0 0-3.4m15.641-3.432a3.432 3.432 0 1 0 0 6.864 3.432 3.432 0 1 0 0-6.864M8.397 16.7a2.75 2.738 0 1 0 0 5.476 2.75 2.738 0 1 0 0-5.476" },
    ],
  },
  "timeline-oldest": {
    filled: false,
    shapes: [
      { kind: 'path', d: "M20.5 5.5v13M3.5 12h17m-6-2.5v5M9 9.5v5M7 8l-4 4 4 4" },
    ],
  },
  "timeline": {
    filled: false,
    shapes: [
      { kind: 'path', d: "M3.5 5.5v13m0-6.5h17m-11-2.5v5m5.5-5v5M17 8l4 4-4 4" },
    ],
  }
};
