// AUTO-GENERATED by scripts/generate-redirects.mjs — do not edit by hand.
// Source: the retired Jekyll site on the `master` branch (_config.yml + collections/),
// resolved against src/content by src/lib/redirect-map.ts. Regenerated on predev/prebuild.
//
// 123 old URLs: 119 resolved to a card, 4 fell back to a lens.
//   arctic: 21/22 resolved
//   currentprojects: 0/1 resolved
//   fatecardgame: 6/6 resolved
//   futureprojects: 3/3 resolved
//   galapagos: 6/6 resolved
//   pastprojects: 15/15 resolved
//   places: 2/2 resolved
//   posts: 52/52 resolved
//   static: 8/10 resolved
//   workhistory: 6/6 resolved

/**
 * Old Jekyll URL → new URL. Consumed by `redirects` in astro.config.mjs, which
 * emits one meta-refresh HTML page per entry in the static build (GitHub Pages
 * has no server-side redirect capability).
 */
export const REDIRECTS: Record<string, string> = {
  "/arctic/0-0-introduction": "/card/what/posts/stories/arctic/00-introduction",
  "/arctic/0-1-map": "/card/what/posts/stories/arctic/00-introduction",
  "/arctic/1-1-glacier": "/card/what/posts/stories/arctic/02-glacier",
  "/arctic/1-2-surge-glacier": "/card/what/posts/stories/arctic/03-surge-glacier",
  "/arctic/1-3-flowers": "/card/what/posts/stories/arctic/04-flowers",
  "/arctic/1-4-reindeer": "/card/what/posts/stories/arctic/05-reindeer",
  "/arctic/1-5-morraine-and-tundra": "/card/what/posts/stories/arctic/06-morraine-and-tundra",
  "/arctic/1-6-fractals-in-mud": "/card/what/posts/stories/arctic/07-fractals-in-mud",
  "/arctic/1-7-cultural-heritage": "/card/what/posts/stories/arctic/08-cultural-heritage",
  "/arctic/1-8-polar-bear-tracks": "/card/what/posts/stories/arctic/09-polar-bear-tracks",
  "/arctic/1-9-polar-bear-encounter": "/card/what/posts/stories/arctic/10-polar-bear-encounter",
  "/arctic/2-1-midnight-sun": "/card/what/posts/stories/arctic/11-midnight-sun",
  "/arctic/2-2-patterns-from-water": "/card/what/posts/stories/arctic/12-patterns-from-water",
  "/arctic/2-3-melting-rocks": "/card/what/posts/stories/arctic/13-melting-rocks",
  "/arctic/2-4-glacier-sound": "/card/what/posts/stories/arctic/14-glacier-sound",
  "/arctic/2-5-the-northernmost-rock": "/card/what/posts/stories/arctic/15-the-northernmost-rock",
  "/arctic/2-6-rock-jenga": "/card/what/posts/stories/arctic/16-rock-jenga",
  "/arctic/3-1-climbing-the-mast": "/card/what/posts/stories/arctic/17-climbing-the-mast",
  "/arctic/3-2-walruses": "/card/what/posts/stories/arctic/18-walruses",
  "/arctic/3-3-plastic": "/card/what/posts/stories/arctic/19-plastic",
  "/arctic/3-4-the-worlds-northernmost-atm": "/card/what/posts/stories/arctic/20-the-worlds-northernmost-atm",
  "/arctic/4-conclusion": "/card/what/posts/stories/arctic/21-conclusion",
  "/cv": "/",
  "/fatecardgame/00-introduction": "/card/what/posts/stories/fatecardgame/00-introduction",
  "/fatecardgame/01-history": "/card/what/posts/stories/fatecardgame/01-history",
  "/fatecardgame/02-themes": "/card/what/posts/stories/fatecardgame/02-themes",
  "/fatecardgame/03-art": "/card/what/posts/stories/fatecardgame/03-art",
  "/fatecardgame/04-fates-hand": "/card/what/posts/stories/fatecardgame/04-fates-hand",
  "/fatecardgame/05-fates-roles": "/card/what/posts/stories/fatecardgame/05-fates-roles",
  "/galapagos/00-introduction": "/card/what/posts/stories/galapagos/00-introduction",
  "/galapagos/01-tourism": "/card/what/posts/stories/galapagos/01-tourism",
  "/galapagos/02-sea-wolves": "/card/what/posts/stories/galapagos/02-sea-wolves",
  "/galapagos/03-stay-away": "/card/what/posts/stories/galapagos/03-stay-away",
  "/galapagos/04-semi-arid": "/card/what/posts/stories/galapagos/04-semi-arid",
  "/galapagos/05-sideways-leaves": "/card/what/posts/stories/galapagos/05-sideways-leaves",
  "/help": "/",
  "/ice": "/",
  "/obs": "https://drive.google.com/drive/folders/1BIuuqsW2uFCa7Iw0fj4vQjJA5L_9nsA9?usp=sharing",
  "/podcast": "/",
  "/what": "/",
  "/what/blog/7-things-that-have-to-work-together-in-a-game-story": "/card/what/writing/2013-04-29-7-things-that-have-to-work-together-in-a-game-story",
  "/what/blog/a-matter-of-perspective": "/card/what/writing/2010-07-10-a-matter-of-perspective",
  "/what/blog/a-particular-vision": "/card/what/writing/2013-06-21-a-particular-vision",
  "/what/blog/achron-real-time-just-got-complicated": "/card/what/writing/2010-06-23-achron-real-time-just-got-complicated",
  "/what/blog/art-or-heist-designing-multipurpose-spaces": "/card/what/writing/2016-12-15-art-or-heist-designing-multipurpose-spaces",
  "/what/blog/blood-and-stakes": "/card/what/writing/2011-02-18-blood-and-stakes",
  "/what/blog/controlling-the-rapids": "/card/what/writing/2011-06-09-controlling-the-rapids",
  "/what/blog/data-that-listens": "/card/what/writing/2016-11-19-data-that-listens",
  "/what/blog/deciding-where-the-heart-is": "/card/what/writing/2019-02-18-deciding-where-the-heart-is",
  "/what/blog/designing-a-budget": "/card/what/writing/2019-03-21-designing-a-budget",
  "/what/blog/edinburgh-reactions-whist": "/card/what/writing/2017-08-12-edinburgh-reactions-whist",
  "/what/blog/ensuring-your-project-has-depth": "/card/what/writing/2013-05-08-ensuring-your-project-has-depth",
  "/what/blog/finding-the-right-problems-for-citizen-science": "/card/what/writing/2016-12-07-finding-the-right-problems-for-citizen-science",
  "/what/blog/finding-the-story": "/card/what/writing/2010-06-27-finding-the-story",
  "/what/blog/getting-social": "/card/what/writing/2013-08-05-getting-social",
  "/what/blog/government-2-0": "/card/what/writing/2017-07-11-government-2-0",
  "/what/blog/having-a-budget": "/card/what/writing/2019-03-11-having-a-budget",
  "/what/blog/holding-things-up-in-two-dimensions": "/card/what/writing/2012-07-09-holding-things-up-in-two-dimensions",
  "/what/blog/how-many-players-should-you-playtest-with": "/card/what/writing/2011-06-18-how-many-players-should-you-playtest-with",
  "/what/blog/how-to-find-your-gameplay-themes": "/card/what/writing/2011-06-09-how-to-find-your-gameplay-themes",
  "/what/blog/inception-the-game": "/card/what/writing/2010-08-02-inception-the-game",
  "/what/blog/innovations-in-games": "/card/what/writing/2013-07-20-innovations-in-games",
  "/what/blog/inspiration-and-emulation": "/card/what/writing/2014-05-08-inspiration-and-emulation",
  "/what/blog/is-affect-the-new-mise-en-scene": "/card/what/writing/2010-07-04-is-affect-the-new-mise-en-scene",
  "/what/blog/its-probably-complicated": "/card/what/writing/2017-11-19-its-probably-complicated",
  "/what/blog/launching-the-bot": "/card/what/writing/2013-03-14-launching-the-bot",
  "/what/blog/making-it-together": "/card/what/writing/2011-11-27-making-it-together",
  "/what/blog/mechanical-breakdown-boss-battles": "/card/what/writing/2011-08-11-mechanical-breakdown-boss-battles",
  "/what/blog/mechanical-breakdown-the-inventory": "/card/what/writing/2010-06-27-mechanical-breakdown-the-inventory",
  "/what/blog/mechanical-breakdown-the-inventory-part-two": "/card/what/writing/2010-08-13-mechanical-breakdown-the-inventory-part-two",
  "/what/blog/mechanical-breakdown-the-rts": "/card/what/writing/2010-06-20-mechanical-breakdown-the-rts",
  "/what/blog/meta-me-this": "/card/what/writing/2011-06-14-meta-me-this",
  "/what/blog/of-shapes-and-flies": "/card/what/writing/2011-09-09-of-shapes-and-flies",
  "/what/blog/on-truth-in-science": "/card/what/writing/2016-05-24-on-truth-in-science",
  "/what/blog/playtesting-101": "/card/what/writing/2011-07-14-playtesting-101",
  "/what/blog/playtesting-102": "/card/what/writing/2011-07-19-playtesting-102",
  "/what/blog/playtesting-103": "/card/what/writing/2011-08-02-playtesting-103",
  "/what/blog/playtesting-104": "/card/what/writing/2011-08-04-playtesting-104",
  "/what/blog/playtesting-105": "/card/what/writing/2011-08-06-playtesting-105",
  "/what/blog/playtesting-106": "/card/what/writing/2011-09-12-playtesting-106",
  "/what/blog/postmortem-the-enemy-of-my-enemy-is-my-heat-seeking-missile": "/card/what/writing/2010-08-26-postmortem-the-enemy-of-my-enemy-is-my-heat-seeking-missile",
  "/what/blog/qbyte-devlog-cycles-and-cul-de-sacs": "/card/what/writing/2017-11-06-qbyte-devlog-cycles-and-cul-de-sacs",
  "/what/blog/qbyte-devlog-taking-the-measure": "/card/what/writing/2017-09-19-qbyte-devlog-taking-the-measure",
  "/what/blog/qbyte-devlog-v0-1-the-simulator-lives": "/card/what/writing/2017-09-24-qbyte-devlog-v0-1-the-simulator-lives",
  "/what/blog/starting-over": "/card/what/writing/2016-05-02-starting-over",
  "/what/blog/the-15-steps-of-particulars-preproduction": "/card/what/writing/2013-03-24-the-15-steps-of-particulars-preproduction",
  "/what/blog/the-a-z-of-game-development": "/card/what/writing/2012-01-06-the-a-z-of-game-development",
  "/what/blog/the-half-cinderella": "/card/what/writing/2011-08-05-the-half-cinderella",
  "/what/blog/the-problem-with-portals": "/card/what/writing/2010-10-17-the-problem-with-portals",
  "/what/blog/the-seethrough-diaries": "/card/what/writing/2012-02-17-the-seethrough-diaries",
  "/what/blog/why-portal": "/card/what/writing/2008-07-27-why-portal",
  "/what/blog/wrecking-the-curve": "/card/what/writing/2010-12-21-wrecking-the-curve",
  "/what/projects/art-heist": "/card/what/art/art-heist",
  "/what/projects/bravehearts": "/card/what/games/digital/bravehearts",
  "/what/projects/budget-haver": "/card/what/software/budget-haver",
  "/what/projects/cybersecurity": "/card/what/games/digital/cybersecurity",
  "/what/projects/fatecardgame": "/lens/newest",
  "/what/projects/flatland-fallen-angle": "/card/what/games/digital/flatland-fallen-angle",
  "/what/projects/genetic-sequences": "/card/what/art/genetic-sequences",
  "/what/projects/gottagetouttathisspace": "/card/what/games/analog/gotta-get-outta-this-space",
  "/what/projects/laser-harp": "/card/what/art/laser-harp",
  "/what/projects/numbeanies": "/card/what/games/digital/numbeanies",
  "/what/projects/particulars": "/card/what/games/digital/particulars",
  "/what/projects/played": "/card/what/games/digital/played",
  "/what/projects/qistigram": "/card/what/art/qistigram",
  "/what/projects/quantum-byte": "/card/what/games/digital/quantum-byte",
  "/what/projects/the-neighbourhood": "/card/what/art/the-neighbourhood",
  "/what/projects/the-path": "/card/what/art/the-path",
  "/what/projects/unstoppabot": "/card/what/games/digital/unstoppabot",
  "/what/projects/virtual-farm": "/card/what/games/digital/virtual-farm",
  "/what/projects/where-the-heart-is": "/card/what/games/digital/where-the-heart-is",
  "/when": "/lens/newest",
  "/where": "/",
  "/where/arctic": "/card/what/posts/stories/arctic/00-introduction",
  "/where/galapagos": "/card/what/posts/stories/galapagos/00-introduction",
  "/who": "/",
  "/why": "/",
  "/workhistory/3p": "/card/where/work/3p",
  "/workhistory/chaostheory": "/card/where/work/chaostheory",
  "/workhistory/dot": "/card/where/work/dot",
  "/workhistory/equalreality": "/card/where/work/equalreality",
  "/workhistory/plan-a": "/card/where/work/plan-a",
  "/workhistory/seethrough": "/card/where/work/seethrough",
};

/**
 * The audit trail: old URLs that could not be resolved to a card and were sent
 * to a lens instead. Never silently dropped — every entry here still has a
 * REDIRECTS row, and the list is asserted against in src/lib/redirect-map.test.ts.
 */
export const UNRESOLVED_OLD_URLS: readonly { from: string; to: string; reason: string }[] = [
  { from: "/arctic/0-1-map", to: "/card/what/posts/stories/arctic/00-introduction", reason: "no match for slug \"0-1-map\"; sent to the start of the \"arctic\" story" },
  { from: "/what/projects/fatecardgame", to: "/lens/newest", reason: "no match for slug \"fatecardgame\"" },
  { from: "/who", to: "/", reason: "no such card: who/about-me" },
  { from: "/cv", to: "/", reason: "no such card: who/about-me" },
];

/**
 * The subset of UNRESOLVED_OLD_URLS traceable to a card that still exists but
 * is unreachable in a production build (`status: draft`/`archived`, or a
 * `scheduled` date not yet reached). Consumed by the audit lens, which lists
 * the offending cards by name — publishing one closes its entry here.
 */
export const ORPHANED_OLD_URLS: readonly { uid: string; from: string; to: string }[] = [
  { uid: "what/posts/stories/arctic/01-map", from: "/arctic/0-1-map", to: "/card/what/posts/stories/arctic/00-introduction" },
  { uid: "what/games/analog/fatecardgame", from: "/what/projects/fatecardgame", to: "/lens/newest" },
  { uid: "who/about-me", from: "/who", to: "/" },
  { uid: "who/about-me", from: "/cv", to: "/" },
];
