// GENERATED by scripts/generate-vimeo-posters.mjs — do not edit.
//
// Vimeo poster (still frame) URLs, keyed by video id, for every Vimeo video
// referenced in src/content. Vimeo has no predictable poster path, so these
// come from its oEmbed API at build time. Re-run `npm run generate:vimeo-posters`
// after adding a Vimeo link; ids already present here are never re-fetched.

export const VIMEO_POSTERS: Record<string, string> = {
};
